#!/usr/bin/env python3.12
"""v2.4.0 — guarantee an adequate warmup + cooldown in every ZWO workout.

Intensity-scaled: hard/intense rides get a longer ramp than easy Z2. A workout
with a missing or too-short warmup/cooldown gets a smooth <Warmup>/<Cooldown>
ramp; the MAIN SET is never touched. Idempotent (skips already-adequate files).
Duration grows where a ramp is added — files are NOT renamed (duration is
content-parsed everywhere; renaming would break zwo_file refs in saved plans).

Usage:
    python3.12 scripts/normalize_warmups.py            # dry-run (report only)
    python3.12 scripts/normalize_warmups.py --apply     # rewrite + back up originals

FIT export is unchanged: the transcoder reads these <Warmup>/<Cooldown> ramps
and staircases them (kept coarse on purpose — no extra device pings).
"""
from __future__ import annotations

import sys
import re
import glob
import os
import shutil
import xml.etree.ElementTree as ET
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKOUTS = os.path.join(ROOT, "workouts")
BACKUP = os.path.expanduser("~/domestique_warmup_backup")

INTENSE = {"vo2max", "vo2_short", "vo2_ladder", "anaerobic", "neuromuscular",
           "threshold", "threshold_ladder", "over_under"}
MODERATE = {"sweet_spot", "sweet_spot_ladder", "tempo", "tempo_intervals", "tempo_ladder"}

# tier -> (warmup_secs, cooldown_secs, ramp_end_cap)
THRESH = {
    "intense":  (600, 300, 0.75),
    "moderate": (480, 180, 0.75),
    "easy":     (240, 120, 0.70),
}


def _classes() -> dict:
    sys.path.insert(0, ROOT)
    import training_planner as tp
    return tp._load_content_classifications() or {}


def tier(primary: str) -> str:
    if primary in INTENSE:
        return "intense"
    if primary in MODERATE:
        return "moderate"
    return "easy"


def _pf(el, *keys, default=0.0) -> float:
    for k in keys:
        v = el.get(k)
        if v is not None:
            try:
                return float(v)
            except ValueError:
                pass
    return default


def _dur(el) -> int:
    return int(_pf(el, "Duration"))


def _is_lead_easy(el) -> bool:
    if el.tag in ("Warmup", "Ramp", "FreeRide"):
        return True
    return el.tag == "SteadyState" and _pf(el, "Power", "PowerLow", default=1.0) < 0.80


def _is_tail_easy(el) -> bool:
    if el.tag in ("Cooldown", "FreeRide"):
        return True
    return el.tag == "SteadyState" and _pf(el, "Power", "PowerHigh", default=1.0) < 0.70


def _effort_power(el, lead: bool) -> float:
    if el.tag == "SteadyState":
        return _pf(el, "Power", default=0.75)
    if el.tag == "IntervalsT":
        return _pf(el, "OnPower", default=0.95)
    if el.tag in ("Warmup", "Ramp", "Cooldown"):
        return _pf(el, "PowerHigh" if lead else "PowerLow", default=0.75)
    return 0.75


def _fmt(p: float) -> str:
    return f"{round(p, 3):g}"


def _total_secs(els) -> int:
    t = 0
    for e in els:
        if e.tag == "IntervalsT":
            r = int(_pf(e, "Repeat", default=1))
            t += r * (int(_pf(e, "OnDuration")) + int(_pf(e, "OffDuration")))
        else:
            t += _dur(e)
    return t


def _refresh_meta(root, total_min, warm_min, warm_end, cool_min, cool_start, did_warm, did_cool):
    """Keep the in-file <name>/<description> honest after a ramp change. The app
    UI uses display_name (regenerated by classification), but trainer apps read
    these — so fix the (NNmin) token + the Warmup/Cooldown description clauses."""
    nm = root.find("name")
    if nm is not None and nm.text and "min)" in nm.text:
        nm.text = re.sub(r"\(\s*\d+\s*min\)", f"({total_min}min)", nm.text)
    de = root.find("description")
    if de is not None and de.text and " | " in de.text:
        parts = de.text.split(" | ")
        if did_warm and parts[0].strip().lower().startswith("warmup"):
            parts[0] = f"Warmup: {warm_min}min ramp from 50% to {round(warm_end * 100)}% FTP"
        if did_cool and parts[-1].strip().lower().startswith("cooldown"):
            parts[-1] = f"Cooldown: {cool_min}min ramp from {round(cool_start * 100)}% to 40% FTP"
        de.text = " | ".join(parts)


def process(path: str, classes: dict, apply: bool):
    """Parse one ZWO, add adequate warmup/cooldown where inadequate, optionally
    write. Returns (changed: bool, note: str)."""
    tree = ET.parse(path)
    wel = tree.getroot().find("workout")
    if wel is None:
        return False, "no <workout>"
    els = list(wel)
    if len(els) < 2:
        return False, "too few elements"

    fn = os.path.basename(path)
    t = tier((classes.get(fn, {}) or {}).get("primary", ""))
    warm_need, cool_need, cap = THRESH[t]

    n = len(els)
    lead = 0
    while lead < n and _is_lead_easy(els[lead]):
        lead += 1
    tail = 0
    while tail < n - lead and _is_tail_easy(els[n - 1 - tail]):
        tail += 1
    warm_s = sum(_dur(e) for e in els[:lead])
    cool_s = sum(_dur(e) for e in els[n - tail:]) if tail else 0
    first_p = _effort_power(els[lead], lead=True) if lead < n else 0.75
    last_p = _effort_power(els[n - 1 - tail], lead=False) if (n - 1 - tail) >= 0 else 0.65

    middle = els[lead: n - tail] if tail else els[lead:]
    if not middle:
        return False, "all warm/cool (skip)"

    # Cap warmup/cooldown so they never exceed the MAIN SET — a short intense
    # workout gets a proportionate (shorter) ramp instead of a fixed 10-min
    # warmup that would dwarf the work and reclassify it as endurance.
    main_secs = _total_secs(middle)
    warm_need = min(warm_need, main_secs)
    cool_need = min(cool_need, main_secs)

    warm_ok = warm_s >= warm_need
    cool_ok = cool_s >= cool_need
    if warm_ok and cool_ok:
        return False, f"adequate ({t})"

    new_children = []
    end = start = None
    wu_el = cd_el = None
    if warm_ok:
        new_children.extend(els[:lead])
    else:
        end = min(max(first_p, 0.6), cap)
        wu_el = ET.Element("Warmup", {
            "Duration": str(warm_need), "PowerLow": "0.5", "PowerHigh": _fmt(end)})
        new_children.append(wu_el)
    new_children.extend(middle)
    if cool_ok:
        new_children.extend(els[n - tail:] if tail else [])
    else:
        start = min(max(last_p, 0.55), cap)
        cd_el = ET.Element("Cooldown", {
            "Duration": str(cool_need), "PowerLow": _fmt(start), "PowerHigh": "0.4"})
        new_children.append(cd_el)

    # Snap the new TOTAL to a whole minute by nudging the ramp we added (cooldown
    # preferred), so the migrated library stays integer-minute — tidy durations +
    # smaller file-vs-plan gaps. Nudge is <60s; never drops a ramp below 30s.
    snap_el = cd_el if cd_el is not None else wu_el
    if snap_el is not None:
        # Round UP to the next whole minute (only ever GROWS the ramp, so a
        # just-adequate ramp never gets trimmed below its threshold — keeps the
        # re-scan at 0 + the migration idempotent).
        delta = (-_total_secs(new_children)) % 60
        if delta:
            snap_el.set("Duration", str(int(snap_el.get("Duration")) + delta))

    fixed = []
    if not warm_ok:
        fixed.append(f"warmup {warm_s}->{warm_need}s")
    if not cool_ok:
        fixed.append(f"cooldown {cool_s}->{cool_need}s")

    if apply:
        shutil.copy2(path, os.path.join(BACKUP, fn))
        for e in list(wel):
            wel.remove(e)
        for e in new_children:
            wel.append(e)
        _refresh_meta(tree.getroot(), round(_total_secs(new_children) / 60),
                      (int(wu_el.get("Duration")) // 60 if wu_el is not None else warm_need // 60),
                      end or 0.0,
                      (int(cd_el.get("Duration")) // 60 if cd_el is not None else cool_need // 60),
                      start or 0.0, not warm_ok, not cool_ok)
        tree.write(path, encoding="UTF-8", xml_declaration=True)

    return True, f"{t}: " + ", ".join(fixed)


def _refresh_classification(changed: set):
    """Refresh ONLY the duration-bearing bits of the classification cache for
    modified files — keep `primary` (a warmup/cooldown change cannot alter a
    workout's training TYPE; a full re-classify would wrongly flip diluted hard
    workouts to endurance). The app uses this cache as-is, so this keeps types
    stable while display names show the new duration."""
    import json
    cache_path = os.path.join(WORKOUTS, ".content_classification.json")
    if not os.path.exists(cache_path):
        return
    with open(cache_path, encoding="utf-8") as f:
        payload = json.load(f)
    cls = payload.get("classifications", {})
    for fn in changed:
        e = cls.get(fn)
        if not e:
            continue
        try:
            wel = ET.parse(os.path.join(WORKOUTS, fn)).getroot().find("workout")
            secs = _total_secs(list(wel))
        except Exception:  # noqa: BLE001
            continue
        new_min = round(secs / 60)
        dn = e.get("display_name") or ""
        if dn and "min" in dn:
            e["display_name"] = re.sub(r"\b\d+\s*min\b", f"{new_min}min", dn, count=1)
        for k in ("duration_min", "duration_sec", "total_sec"):
            if k in e:
                e[k] = new_min if k == "duration_min" else secs
    sys.path.insert(0, ROOT)
    import training_planner as tp
    payload["workouts_dir_hash"] = tp._compute_workouts_dir_hash()
    with open(cache_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
    print(f"refreshed classification display-names for {len(changed)} files (primary preserved)")


def main():
    apply = "--apply" in sys.argv
    classes = _classes()
    files = sorted(glob.glob(os.path.join(WORKOUTS, "*.zwo")))
    if apply:
        os.makedirs(BACKUP, exist_ok=True)
    by_tier = Counter()
    changed = 0
    changed_files = []
    samples = []
    for p in files:
        try:
            did, note = process(p, classes, apply)
        except Exception as e:  # noqa: BLE001
            print(f"  ERR {os.path.basename(p)}: {e}")
            continue
        if did:
            changed += 1
            changed_files.append(os.path.basename(p))
            by_tier[note.split(":")[0]] += 1
            if len(samples) < 8:
                samples.append((os.path.basename(p), note))
    if apply and changed_files:
        _refresh_classification(set(changed_files))
    print(f"\n{'APPLIED' if apply else 'DRY-RUN'} — {changed}/{len(files)} files need warmup/cooldown work")
    print("by tier:", dict(by_tier))
    print("samples:")
    for nm, note in samples:
        print(f"  {nm}: {note}")
    if not apply:
        print("\nRe-run with --apply to rewrite (originals -> ~/domestique_warmup_backup).")


if __name__ == "__main__":
    main()
